name: common-windows-x86-64

on:
  #push:
  #  branches: [ master ]
  #  paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md]
  pull_request:
    branches: [ master ]
    paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md,
                   'cmake/arm.cmake', 'cmake/cuda.cmake', 'cmake/riscv.cmake',
                   'include/ppl/nn/engines/arm/**', 'src/ppl/nn/engines/arm/**',
                   'include/ppl/nn/engines/cuda/**', 'src/ppl/nn/engines/cuda/**',
                   'include/ppl/nn/engines/riscv/**', 'src/ppl/nn/engines/riscv/**']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.run_id }}--${{ github.ref }}--${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: [self-hosted, x64, windows]

    steps:
      - name: Create Checkout Directory
        run: |
          cd ../../ ; ./make_pplnn_dir.ps1 ${{ github.run_id }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.run_id }}

      - name: Build
        run: |
          cd ../../ ; ./build.ps1 ${{ github.run_id }} x86_64

      - name: Cleanup
        if: ${{ always() }}
        run: |
          cd ../../ ; ./clean.ps1 ${{ github.run_id }} x86_64
